"""empty message

Revision ID: 4bfc666ef6be
Revises: c34567c261dd
Create Date: 2024-01-24 12:33:22.641947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfc666ef6be'
down_revision = 'c34567c261dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(length=50), nullable=False))
        batch_op.drop_column('instruction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
